services:
  - type: web
    name: neenu-natural-fullstack
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: "/api/health"
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 8080
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: neenu-natural-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: neenu-natural-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: neenu-natural-db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: false
      - key: SPRING_JPA_DATABASE_PLATFORM
        value: org.hibernate.dialect.PostgreSQLDialect

databases:
  - name: neenu-natural-db
    databaseName: neenu_natural
    plan: free